import { useEffect, useState } from "react";
import api from "../../services/api";
import { ErrorBox, Form, Loading, Modal, Page } from "./AdminUI";

const fields = [
  { name: "name", label: "Village name", required: true }, { name: "district", label: "District", required: true }, { name: "state", label: "State", required: true }, { name: "pincode", label: "Pincode" },
  { name: "population", label: "Population", type: "number" }, { name: "area", label: "Area (sq km)", type: "number" }, { name: "description", label: "Description", type: "textarea", full: true },
  { name: "sarpanchName", label: "Sarpanch name" }, { name: "sarpanchPhone", label: "Sarpanch phone" }, { name: "isActive", label: "Public village profile active", type: "checkbox" },
];

export default function VillageSettings() {
  const [village, setVillage] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState(false); const [uploading, setUploading] = useState(false); const [files, setFiles] = useState([]);
  const load = async () => { setLoading(true); setError(""); try { const response = await api.get("/village"); setVillage(response.data?.data?.village || null); } catch (err) { if (err.response?.status === 404) setVillage(null); else setError(err.response?.data?.message || "Failed to load village"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (form) => { const data = { name: form.name, district: form.district, state: form.state, pincode: form.pincode, population: Number(form.population || 0), area: Number(form.area || 0), description: form.description, isActive: Boolean(form.isActive), sarpanch: { name: form.sarpanchName || "", phone: form.sarpanchPhone || "" }, places: village?.places || [] }; try { const response = village ? await api.put(`/village/${village._id}`, data) : await api.post("/village", data); setVillage(response.data?.data?.village || village); setEditing(false); } catch (err) { setError(err.response?.data?.message || "Save failed"); } };
  const uploadImages = async () => { if (!village?._id || !files.length) return; setUploading(true); setError(""); try { const body = new FormData(); files.forEach((file) => body.append("images", file)); const response = await api.post(`/village/${village._id}/images`, body, { headers: { "Content-Type": "multipart/form-data" } }); setVillage(response.data?.data?.village || village); setFiles([]); } catch (err) { setError(err.response?.data?.message || "Image upload failed"); } finally { setUploading(false); } };
  if (loading) return <Page title="Village Settings"><Loading /></Page>;
  const initial = village ? { ...village, population: village.population || 0, area: village.area || 0, sarpanchName: village.sarpanch?.name || "", sarpanchPhone: village.sarpanch?.phone || "", isActive: village.isActive !== false } : { population: 0, area: 0, isActive: true };
  return <Page title="Village Settings" subtitle="Live village profile management. Changes are saved directly to the backend database." actions={<button className="btn-primary" onClick={() => setEditing(true)} type="button">{village ? "Edit details" : "Create village profile"}</button>}>
    {error ? <ErrorBox message={error} retry={load} /> : null}
    {village ? <>
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="card p-6 lg:col-span-2"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold">{village.name}</h2><p className="mt-1 text-gray-500">{village.district}, {village.state} {village.pincode ? `· ${village.pincode}` : ""}</p></div><span className={`badge ${village.isActive ? "badge-green" : "badge-red"}`}>{village.isActive ? "Public Active" : "Public Inactive"}</span></div><p className="mt-5 whitespace-pre-wrap text-sm text-gray-600 dark:text-gray-300">{village.description || "No description added."}</p><div className="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4"><div><p className="text-xs text-gray-500">Population</p><p className="font-semibold">{village.population || 0}</p></div><div><p className="text-xs text-gray-500">Area</p><p className="font-semibold">{village.area || 0} sq km</p></div><div><p className="text-xs text-gray-500">Places</p><p className="font-semibold">{village.places?.length || 0}</p></div><div><p className="text-xs text-gray-500">Images</p><p className="font-semibold">{village.images?.length || 0}</p></div></div></div>
        <div className="card p-6"><h3 className="font-semibold">Sarpanch</h3><p className="mt-3 text-lg">{village.sarpanch?.name || "Not set"}</p><p className="text-sm text-gray-500">{village.sarpanch?.phone || "No phone added"}</p></div>
      </div>
      <div className="card p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Village images</h3><p className="text-sm text-gray-500">Upload up to 5 images at a time through the existing backend endpoint.</p></div><div className="flex flex-wrap gap-2"><input type="file" accept="image/*" multiple onChange={(e) => setFiles(Array.from(e.target.files || []).slice(0, 5))} className="input max-w-sm" /><button className="btn-primary" disabled={!files.length || uploading} onClick={uploadImages} type="button">{uploading ? "Uploading..." : "Upload images"}</button></div></div>{files.length ? <p className="mt-2 text-xs text-gray-500">Selected: {files.map((f) => f.name).join(", ")}</p> : null}<div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(village.images || []).map((image) => <img key={image.publicId || image.url} src={image.url} alt={image.caption || village.name} className="h-36 w-full rounded-xl object-cover" />)}</div></div>
    </> : <div className="card p-8 text-center text-gray-500">No village profile exists yet. Create it to populate the public village pages.</div>}
    {editing ? <Modal title={village ? "Edit Village" : "Create Village"} onClose={() => setEditing(false)} wide><Form fields={fields} initial={initial} onSubmit={save} submitLabel={village ? "Save changes" : "Create profile"} onCancel={() => setEditing(false)} /></Modal> : null}
  </Page>;
}
